#!/usr/bin/env bash
# Generates the Python stubs of the EDGE contract (dop.bff.v1).
#
# The essential difference from gen_proto.sh: these .proto files are OURS — they
# live in this repository (api/proto), because the one that defines the edge's
# contract is the BFF. The core's live in dop-core and are only consumed here.
#
# The output directory is regenerable and is not edited by hand.
#
# Usage:
#   ./scripts/gen_bff_proto.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_ROOT="${DOP_BFF_PROTO:-$ROOT/api/proto}"
OUT="$ROOT/app/grpcapi/gen"
PKG="app.grpcapi.gen"

if [[ ! -d "$PROTO_ROOT/dop/bff/v1" ]]; then
  echo "error: no edge protos found at $PROTO_ROOT" >&2
  exit 1
fi

echo "protos: $PROTO_ROOT"
echo "output: $OUT"

rm -rf "$OUT"
mkdir -p "$OUT"

# -I at the protos' ROOT: the import path ("dop/bff/v1/identity.proto") is what
# becomes the generated module's path.
uv run python -m grpc_tools.protoc \
  -I "$PROTO_ROOT" \
  --python_out="$OUT" \
  --pyi_out="$OUT" \
  --grpc_python_out="$OUT" \
  "$PROTO_ROOT"/dop/bff/v1/*.proto

# ── the same import problem as gen_proto.sh ─────────────────────────────────
# protoc generates "from dop.bff.v1 import identity_pb2", which would only
# resolve with `gen/` at the root of sys.path. Touching sys.path at runtime
# breaks in ways that are hard to debug (and differently under pytest and under
# uvicorn), so we rewrite the import to the package's real path: deterministic,
# visible in the diff, and the rest of the app imports it like any other module.
uv run python - "$OUT" "$PKG" <<'PY'
import pathlib
import re
import sys

out, pkg = pathlib.Path(sys.argv[1]), sys.argv[2]
pattern = re.compile(r"^from dop\.bff\.v1 import ", flags=re.MULTILINE)
touched = 0
for path in sorted([*out.rglob("*.py"), *out.rglob("*.pyi")]):
    text = path.read_text(encoding="utf-8")
    new = pattern.sub(f"from {pkg}.dop.bff.v1 import ", text)
    if new != text:
        path.write_text(new, encoding="utf-8")
        touched += 1
print(f"imports rewritten in {touched} file(s)")
PY

# Real packages (with an __init__.py), not implicit namespace packages: that way
# hatchling's packaging takes the stubs along.
for dir in "$OUT" "$OUT/dop" "$OUT/dop/bff" "$OUT/dop/bff/v1"; do
  cat > "$dir/__init__.py" <<'PY'
"""Generated by scripts/gen_bff_proto.sh from api/proto. Do not edit."""
PY
done

echo "ok: $(find "$OUT" -name '*_pb2.py' | wc -l) message modules, $(find "$OUT" -name '*_pb2_grpc.py' | wc -l) service modules"
