#!/usr/bin/env bash
# Generates the Python stubs from dop-core's .proto files.
#
# The contracts are the SOURCE OF TRUTH and live in dop-core (api/proto). Here
# they are only generated — nothing in this directory is edited by hand.
#
# Usage:
#   ./scripts/gen_proto.sh                 # uses ../dop-core/api/proto
#   DOP_CORE_PROTO=/path ./scripts/gen_proto.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_ROOT="${DOP_CORE_PROTO:-$(cd "$ROOT/.." && pwd)/dop-core/api/proto}"
OUT="$ROOT/app/coreclient/gen"
PKG="app.coreclient.gen"

if [[ ! -d "$PROTO_ROOT/dop/v1" ]]; then
  echo "error: no protos found at $PROTO_ROOT" >&2
  echo "       point DOP_CORE_PROTO at <dop-core>/api/proto" >&2
  exit 1
fi

echo "protos: $PROTO_ROOT"
echo "output: $OUT"

rm -rf "$OUT"
mkdir -p "$OUT"

# -I at the protos' ROOT: the import path ("dop/v1/common.proto") is what
# becomes the generated module's path. The well-known types (timestamp, struct)
# already come in grpc_tools' built-in include.
uv run python -m grpc_tools.protoc \
  -I "$PROTO_ROOT" \
  --python_out="$OUT" \
  --pyi_out="$OUT" \
  --grpc_python_out="$OUT" \
  "$PROTO_ROOT"/dop/v1/*.proto

# ── the import problem ──────────────────────────────────────────────────────
# protoc generates "from dop.v1 import common_pb2", which only resolves if
# `gen/` is at the root of sys.path. Rather than touching sys.path at runtime
# (which breaks in ways that are hard to debug), we rewrite the import to the
# package's real path. Deterministic, visible in the diff, and the rest of the
# app imports it like any other module.
uv run python - "$OUT" "$PKG" <<'PY'
import pathlib
import re
import sys

out, pkg = pathlib.Path(sys.argv[1]), sys.argv[2]
pattern = re.compile(r"^from dop\.v1 import ", flags=re.MULTILINE)
touched = 0
for path in sorted([*out.rglob("*.py"), *out.rglob("*.pyi")]):
    text = path.read_text(encoding="utf-8")
    new = pattern.sub(f"from {pkg}.dop.v1 import ", text)
    if new != text:
        path.write_text(new, encoding="utf-8")
        touched += 1
print(f"imports rewritten in {touched} file(s)")
PY

# Real packages (with an __init__.py), not implicit namespace packages: that way
# hatchling's packaging takes the stubs along.
for dir in "$OUT" "$OUT/dop" "$OUT/dop/v1"; do
  cat > "$dir/__init__.py" <<'PY'
"""Generated by scripts/gen_proto.sh from dop-core's .proto files. Do not edit."""
PY
done

echo "ok: $(find "$OUT" -name '*_pb2.py' | wc -l) message modules, $(find "$OUT" -name '*_pb2_grpc.py' | wc -l) service modules"
